// Creator Hub Creator Network — browser-safe runtime configuration.
// Private service credentials MUST remain in the deployed backend environment.
//
// Browser-safe:
// - Supabase project URL
// - Supabase publishable key
// - LiveKit WebSocket URL
// - public API endpoints
//
// NEVER place these in this file:
// - Supabase service-role/secret key
// - LiveKit API secret
// - PayPal client secret
// - private signing credentials

(function () {
  'use strict';

  var configuredBase = 'https://creator-hub-live-02c1.onrender.com';

  var CreatorHubConfig = {
    app: {
      name: 'Creator Hub Creator Network',
      project: 'creator-hub-live',
      environment: 'production',
      currency: 'JMD',
      locale: 'en-JM'
    },

    supabase: {
      url: 'https://txibryhznycmuqufnxvh.supabase.co',
      restUrl: 'https://txibryhznycmuqufnxvh.supabase.co/rest/v1/',
      publishableKey: 'sb_publishable_ewC8MT1HSsDLA5EyDV-PIg_vrZecqUY'
    },

    livekit: {
      projectId: 'p_4ia809byg35',
      url: 'wss://creator-hub-live-9susyfri.livekit.cloud',
      websocketUrl: 'wss://creator-hub-live-9susyfri.livekit.cloud',

      // LiveKit tokens are generated by the Creator Hub backend.
      tokenEndpoint: '/api/livekit/token',

      healthEndpoint: '/api/livekit/health'
    },

    api: {
      baseUrl: configuredBase,

      healthPath: '/api/health',
      publicConfigPath: '/api/config/public',

      livekitTokenPath: '/api/livekit/token',
      livekitHealthPath: '/api/livekit/health',

      liveRoomsPath: '/api/live/rooms',

      payments: {
        createOrderPath: '/api/payments/create-order',
        captureOrderPath: '/api/payments/capture-order',
        webhookPath: '/api/payments/webhook',
        refundPath: '/api/payments/refund'
      },

      wallet: {
        balancePath: '/api/wallet/balance',
        transactionsPath: '/api/wallet/transactions',
        depositPath: '/api/wallet/deposit',
        withdrawPath: '/api/wallet/withdraw',
        purchasePath: '/api/wallet/purchase',
        giftPath: '/api/wallet/gift'
      },

      leagues: {
        path: '/api/leagues',
        standingsPath: '/api/leagues/standings'
      }
    },

    wallet: {
      currency: 'JMD'
    },

    storage: {
      url: 'https://txibryhznycmuqufnxvh.supabase.co',

      // The real production bucket name must come from the actual
      // Supabase Storage configuration. Never invent one.
      bucket: ''
    },

    maps: {
      provider: 'OpenStreetMap',
      tileUrl: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
    },

    social: {
      tiktokUsername: 'creatorhubcreatornetwork'
    },

    features: {
      livekit: true,
      paypal: true,
      maps: true,
      storage: true
    },

    version: '3.2.0',

    debug: false
  };

  /*
   * -----------------------------------------------------------------------
   * BACKWARD-COMPATIBLE CONFIGURATION ALIASES
   * -----------------------------------------------------------------------
   * Existing Creator Hub pages may use these older names.
   * Keep them so existing functionality is not unnecessarily broken.
   */

  CreatorHubConfig.SUPABASE_URL =
    CreatorHubConfig.supabase.url;

  CreatorHubConfig.SUPABASE_PUBLISHABLE_KEY =
    CreatorHubConfig.supabase.publishableKey;

  // Legacy alias.
  // This remains the PUBLIC browser key, never the service-role key.
  CreatorHubConfig.SUPABASE_ANON_KEY =
    CreatorHubConfig.supabase.publishableKey;

  CreatorHubConfig.API_BASE =
    CreatorHubConfig.api.baseUrl;

  CreatorHubConfig.API_URL =
    CreatorHubConfig.api.baseUrl;

  CreatorHubConfig.BACKEND_URL =
    CreatorHubConfig.api.baseUrl;

  CreatorHubConfig.LIVEKIT_URL =
    CreatorHubConfig.livekit.url;

  CreatorHubConfig.LIVEKIT_WEBSOCKET_URL =
    CreatorHubConfig.livekit.websocketUrl;

  // Intentionally NOT a real LiveKit credential.
  // LiveKit API credentials belong exclusively to backend environment variables.
  CreatorHubConfig.LIVEKIT_API_KEY =
    'API_KEY_IS_NOT_REQUIRED_IN_BROWSER_REQUESTS';

  // PayPal credentials are never stored in browser configuration.
  // Actual PayPal mode is controlled by the backend.
  CreatorHubConfig.PAYPAL_ENVIRONMENT =
    'sandbox';

  CreatorHubConfig.TIKTOK_USERNAME =
    CreatorHubConfig.social.tiktokUsername;

  CreatorHubConfig.BRAND =
    CreatorHubConfig.app.name;

  CreatorHubConfig.APP_NAME =
    CreatorHubConfig.app.name;

  CreatorHubConfig.ENVIRONMENT =
    CreatorHubConfig.app.environment;

  CreatorHubConfig.VERSION =
    CreatorHubConfig.version;

  CreatorHubConfig.API_VERSION =
    'v1';

  CreatorHubConfig.DEBUG =
    CreatorHubConfig.debug;

  /*
   * -----------------------------------------------------------------------
   * GLOBAL CONFIGURATION REFERENCES
   * -----------------------------------------------------------------------
   */

  window.CreatorHubConfig = CreatorHubConfig;
  window.CHL_CONFIG = CreatorHubConfig;
  window.APP_CONFIG = CreatorHubConfig;

  window.CREATOR_HUB_API_BASE =
    CreatorHubConfig.api.baseUrl;

})();
